### PR TITLE
BUGFIX: Data blocks don't need to be in alignment.

### PR DESCRIPTION
**Pull request by ris-home**
Fix an overseen error. Was discovered due to a panic.

### CODE REVIEW

**Comment by ris-home** [comment]
This was discovered by me playing around with various values for BLOCK_SIZE.

**Review by aminya — APPROVED** [review]

**Comment by aminya** [comment]
@narumatt Could you merge this if possible?

**Comment by ris-work** [comment]
@aminya: Considering that it's a critical bugfix and the author hasn't responded for a while, I believe that they could be employed at a company with a _no off-time work_ policy or _off-time IP belongs to us_ policy. I have been employed at such a company before.

Please see my fork if you are interested, it has critical bugfixes, advanced features and was upgraded for a later version of Rust and CLAP: [sqlitefs](https://github.com/ris-work/sqlitefs).
Thank you!

**Review by ris-work — COMMENTED** [review]
It's been over two years; please merge if you have no objections! Thanks!

**Comment by narumatt** [comment]
Sorry for not responding for a long time.
And thanks for improving this project in your fork.

**Pull request merged**
